####################################
# ANYPOINT PLATFORM
####################################
user:
  credentials:
    username: '![ker7rP7wdgmUa7jxwvKVsw==]'
    password: '![8CuX398RQTSSl5UGEohHFQ==]'