####################################
# DEPLOYMENT ENVIRONMENT
####################################
deployment:
  environment: "dev"


####################################
# HTTP/HTTPS CONFIGURATIONS
####################################
http:
  private:
    port: "8081"
    
https:
  private:
    port: "8082"